### PR TITLE
Add retry configuration for all HTTP requests

### LINKED ISSUE #19: Retry uploads on 5xx failures
Currently, uploads potentially fail which is an issue if multiple files are being uploaded from the CI since the CI job cannot be re-run due to duplicate uploads.

Alternatively, `quetz-client` should have an option to not fail on a 409 status code.

### PR DESCRIPTION
**Pull request by borchero**
Resolves #19.

### CODE REVIEW

**Review by janjagusch — CHANGES_REQUESTED** [review]
Thanks for your PR, @borchero. I prefer to include an opinionated Retry config in the client (it might work for you, but maybe that's not what other's would expect). The `session` attribute is public so you can configure it to your needs after instantiation.

I'm considering adding a simple retry mechanism to the CLI tool, though, which might interest you. I'll ping you for review once I've settled for a design.

**Comment by borchero** [comment]
> I'm considering adding a simple retry mechanism to the CLI tool, though, which might interest you. I'll ping you for review once I've settled for a design.

Yes, that would solve #19 as well, thanks :)

**Comment by janjagusch** [comment]
@borchero, would you like to implement this similarly to https://github.com/mamba-org/quetz-client/pull/21?

**Comment by borchero** [comment]
@janjagusch yes! Will open a separate PR for that.

**Pull request closed without merging**
